AWSTemplateFormatVersion: 2010-09-09
Description: Creating a s3 Bucket

Parameters:
  BucketName:
    Description: Domain name for your website (example.com)
    Type: String

Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

Outputs:
  WebsiteURL:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for website hosted on S3