# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy-1:
    runs-on: ubuntu-latest
    steps:
      - name: test.onenine.cloud deploy changes
        uses: actions/checkout@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
      - name: ssh and sudo
        run: echo "$SSH_PRIVATE_KEY" > OneNineAI.pem && chmod 400 OneNineAI.pem
          ssh -o StrictHostKeyChecking=no -i OneNineAI.pem ${REMOTE_USER}@${REMOTE_HOST}

          sudo -s
          echo $pwd
